FORMAT: 1A
HOST: localhost/

# UAS

Polls is a simple API allowing consumers to view polls and vote in them.

## Data - Data Pekerja [/uas]

### Semua List Pekerja [GET/uas/get.php]

+ Response 200 (application/json)

        [
            {
            "Data Pekerjaan": [
                    {
            "id_pekerja": "1",
            "nama_pekerja": "David",
            "umur_pekerja": "65",
            "nama_pekerjaan": "General Manager",
            "alamat_pekerja": "Jln. Medan"
        },
        {
            "id_pekerja": "10",
            "nama_pekerja": "",
            "umur_pekerja": "0",
            "nama_pekerjaan": "",
            "alamat_pekerja": ""
        },
        {
            "id_pekerja": "11",
            "nama_pekerja": "",
            "umur_pekerja": "0",
            "nama_pekerjaan": "",
            "alamat_pekerja": ""
        },
        {
            "id_pekerja": "13",
            "nama_pekerja": "ordrick",
            "umur_pekerja": "52",
            "nama_pekerjaan": "sales manager",
            "alamat_pekerja": "Jln. gunting"
        },
        {
            "id_pekerja": "14",
            "nama_pekerja": "ordrick",
            "umur_pekerja": "21",
            "nama_pekerjaan": "sales",
            "alamat_pekerja": "Jln. Hamid"
        }
                ]
            }
        ]

### Membuat data pekerja baru [POST]

untuk menambah pekerja baru

+ Request (application/json)

        {
        "Data Pekerjaan": [
        {
            "id_pekerja": "ID pekerja",
            "nama_pekerja": "nama pekerja",
            "umur_pekerja": "umur pekerja",
            "nama_pekerjaan": "nama / pangkatan pekerjaan",
            "alamat_pekerja": "alamat pekerja"
        }
        ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /uas/post

    + Body

            {
            "Data Pekerjaan": [
            {
                "id_pekerja": "",
                "nama_pekerja": "",
                "umur_pekerja": "",
                "nama_pekerjaan": "",
                "alamat_pekerja": ""
            },
            ]
            }
            
### Mengedit data pekerja [PUT]

untuk meng-edit pekerja 

+ Request (application/json)

        {
        "Data Pekerjaan": [
        {
            "id_pekerja": "ID pekerja",
        }
        ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /uas/put

    + Body

            {
            "Data Pekerjaan": [
            {
                "id_pekerja": "",
                "nama_pekerja": "",
                "umur_pekerja": "",
                "nama_pekerjaan": "",
                "alamat_pekerja": ""
            },
            ]
            }
            
### Menghapus data pekerja [DELETE/uas/delete]

untuk menghapus pekerja 

+ Request (application/json)

        {
        "Data Pekerjaan": [
        {
            "id_pekerja": "ID pekerja",
        }
        ]
        }
        
        + Response 201 (application/json)

    + Headers

            Location: /uas/delete

    + Body

            {
            " berhasil terhapus "
            ]
            }